host: $REMOTE_HOST
user: $REMOTE_USER 

copy:
  - from: slurm.sh
    to: slurm.sh
    overwrite: true

  - from: collect_data.py
    to: collect_data.py
    overwrite: true

  - from: config.py
    to: config.py
    overwrite: true

collect:
  - from: log-collect-data.log
    to: log-collect-data.log
    overwrite: true

  - from: collected-data.pkl
    to: collected-data.pkl
    overwrite: true
  
  - from: broken-symlinks.log
    to: broken-symlinks.log
    overwrite: true

clean:
  - slurm.sh
  - config.py
  - collect_data.py
  - log-collect-data.log
  - collected-data.pkl
  - broken-symlinks.log

sbatch: slurm.sh
continue_if_job_fails: true
