host: $REMOTE_HOST
user: $REMOTE_USER 

copy:
  - from: slurm.sh
    to: slurm.sh
    overwrite: true

  - from: .
    to: all-package-index/
    overwrite: true

collect:
  - from: all-package-index/log-collect-data.log
    to: log-collect-data.log
    overwrite: true

  - from: all-package-index/collected-data.pkl
    to: collected-data.pkl
    overwrite: true
  
  - from: all-package-index/broken-symlinks.log
    to: broken-symlinks.log
    overwrite: true

  - from: slurm.out 
    to: slurm.out
    overwrite: true

clean:
  - slurm.sh

sbatch: slurm.sh
continue_if_job_fails: true
